[tool.poetry]
name = "oobleck"
version = "0.1.0"
description = "Resilient Distributed Training Framework"
authors = ["Insu Jang <insujang@umich.edu>"]
readme = "README.md"

[build-system]
requires = ["setuptools", "pybind11"]
build-backend = "setuptools.build_meta"
