OOBLECK_RECONFIGURATION = "oobleck/reconfiguration"
OOBLECK_WORLD_INFO = "oobleck/world_info"
OOBLECK_TOPOLOGY_INFO = "oobleck/topology_info"
OOBLECK_TRAINING_IN_PROGRESS = "oobleck/training_in_progress"
OOBLECK_TORCH_MASTER_INFO = "oobleck/torch_master_info"
