from typing import List, Tuple

class StageExecutionResult:
    def get_layer_indices() -> List[int]: ...
    def get_num_gpus() -> int: ...
    def get_memory_consumption() -> int: ...

class PipelineTemplate:
    def get_iteration_time() -> float: ...
    def get_stages() -> List[StageExecutionResult]: ...
    def get_num_nodes() -> int: ...
    def get_num_gpus_per_node() -> int: ...

class PipelineTemplateGenerator:
    def __init__(): ...
    def create_pipeline_templates(
        model_name: str,
        model_tag: str,
        microbatch_size: int,
        num_nodes: Tuple[int, int],
        num_gpus_per_node: int,
    ) -> List[PipelineTemplate]: ...
