# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import master_service_pb2 as master__service__pb2


class OobleckMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDistInfo = channel.unary_unary(
            "/OobleckMaster/GetDistInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=master__service__pb2.DistInfo.FromString,
        )
        self.GetCode = channel.unary_unary(
            "/OobleckMaster/GetCode",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=master__service__pb2.CodeInfo.FromString,
        )
        self.SendMasterRankPort = channel.unary_unary(
            "/OobleckMaster/SendMasterRankPort",
            request_serializer=master__service__pb2.PortInfo.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.ReceiveMasterRankPort = channel.unary_unary(
            "/OobleckMaster/ReceiveMasterRankPort",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=master__service__pb2.PortInfo.FromString,
        )
        self.ReceiveReconfigurationNotification = channel.unary_stream(
            "/OobleckMaster/ReceiveReconfigurationNotification",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=master__service__pb2.DistInfo.FromString,
        )


class OobleckMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDistInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendMasterRankPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReceiveMasterRankPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReceiveReconfigurationNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OobleckMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetDistInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetDistInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=master__service__pb2.DistInfo.SerializeToString,
        ),
        "GetCode": grpc.unary_unary_rpc_method_handler(
            servicer.GetCode,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=master__service__pb2.CodeInfo.SerializeToString,
        ),
        "SendMasterRankPort": grpc.unary_unary_rpc_method_handler(
            servicer.SendMasterRankPort,
            request_deserializer=master__service__pb2.PortInfo.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "ReceiveMasterRankPort": grpc.unary_unary_rpc_method_handler(
            servicer.ReceiveMasterRankPort,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=master__service__pb2.PortInfo.SerializeToString,
        ),
        "ReceiveReconfigurationNotification": grpc.unary_stream_rpc_method_handler(
            servicer.ReceiveReconfigurationNotification,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=master__service__pb2.DistInfo.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "OobleckMaster", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class OobleckMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDistInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/OobleckMaster/GetDistInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            master__service__pb2.DistInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetCode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/OobleckMaster/GetCode",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            master__service__pb2.CodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SendMasterRankPort(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/OobleckMaster/SendMasterRankPort",
            master__service__pb2.PortInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReceiveMasterRankPort(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/OobleckMaster/ReceiveMasterRankPort",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            master__service__pb2.PortInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReceiveReconfigurationNotification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/OobleckMaster/ReceiveReconfigurationNotification",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            master__service__pb2.DistInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
